#!/bin/sh
export MONGO_PORT=27017
pm2 kill
pushd tool-bootstrap
npm install
npm link
popd

pushd pmtool/tp
npm install
npm link tool-bootstrap
env PORT=3333 npm start
popd

pushd codetool/github
npm install
npm link tool-bootstrap
env PORT=3334 npm start
popd

pushd buildtool/travis
npm install
npm link tool-bootstrap
env PORT=3335 npm start
popd

pm2 list