#!/bin/sh
export MONGO_PORT=27017
pm2 kill
cd tool-bootstrap
npm install
npm link
cd ..

cd pmtool/tp
npm install
npm link tool-bootstrap
env PORT=3333 npm start
cd ../..

cd codetool/github
npm install
npm link tool-bootstrap
env PORT=3334 npm start
cd ../..

pushd buildtool/travis
npm install
npm link tool-bootstrap
env PORT=3335 npm start
cd ../..

pm2 list